/*
 *  author   : Mr. Gao
 *
 *  function : To deal with packet structure.
 */

#ifndef __STRUCTURE_H__
#define __STRUCTURE_H__

/* Layer 2 */
#define MACOFFSET \
	PKTHDRLEN
#define VLAN1OFFSET \
	(MACHDRLEN + PKTHDRLEN)
#define VLAN2OFFSET \
	(MACHDRLEN + VLANLEN + PKTHDRLEN)
#define ARPOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + PKTHDRLEN)

/* Layer 3 */
#define IPOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + PKTHDRLEN)
#define ICMPv4OFFSET(n) \
	(MACHDRLEN + n * VLANLEN + IP4HDRLEN + PKTHDRLEN)

/* Layer 4 */
#define UDPOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + PKTHDRLEN)
#define TCPOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + PKTHDRLEN)

/* Layer 7 */
#define DNSOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + UDPHDRLEN + PKTHDRLEN)
#define DNSDATAOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + UDPHDRLEN + DNSHDRLEN + PKTHDRLEN)
#define UDPDATAOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + UDPHDRLEN + PKTHDRLEN)
#define UDPPAYLEN(pkt_len, n) \
	(pkt_len - MACHDRLEN - n*VLANLEN - IP4HDRLEN - UDPHDRLEN)
#define TCPDATAOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + TCPHDRLEN + PKTHDRLEN)
#define TCPPAYLEN(pkt_len, n) \
	(pkt_len - MACHDRLEN - n*VLANLEN - IP4HDRLEN - TCPHDRLEN)
#define ICMPv4DATAOFFSET(n) \
	(MACHDRLEN + n*VLANLEN + IP4HDRLEN + ICMPv4HDRLEN + PKTHDRLEN)
#define ICMPv4PAYLEN(pkt_len, n) \
	(pkt_len - MACHDRLEN - n*VLANLEN - IP4HDRLEN - ICMPv4HDRLEN)

#endif

